function [fitresult, gof] = createFits1(xaxis, curvefit_threshnorm_01, curvefit_threshnorm_05, curvefit_threshnorm_09, curvefit_bayesnorm_01, curvefit_bayesnorm_05, curvefit_bayesnorm_09, rewrange, curvefit_rewthresh_01, curvefit_rewthresh_05, curvefit_rewthresh_09, curvefit_rewbayes_01, curvefit_rewbayes_05, curvefit_rewbayes_09)
%CREATEFITS1(XAXIS,CURVEFIT_THRESHNORM_01,CURVEFIT_THRESHNORM_05,CURVEFIT_THRESHNORM_09,CURVEFIT_BAYESNORM_01,CURVEFIT_BAYESNORM_05,CURVEFIT_BAYESNORM_09,REWRANGE,CURVEFIT_REWTHRESH_01,CURVEFIT_REWTHRESH_05,CURVEFIT_REWTHRESH_09,CURVEFIT_REWBAYES_01,CURVEFIT_REWBAYES_05,CURVEFIT_REWBAYES_09)
%  Create fits.
%
%  Data for 'ThreshNorm01' fit:
%      X Input : xaxis
%      Y Output: curvefit_threshnorm_01
%  Data for 'ThreshNorm05' fit:
%      X Input : xaxis
%      Y Output: curvefit_threshnorm_05
%  Data for 'ThreshNorm09' fit:
%      X Input : xaxis
%      Y Output: curvefit_threshnorm_09
%  Data for 'BayesNorm01' fit:
%      X Input : xaxis
%      Y Output: curvefit_bayesnorm_01
%  Data for 'BayesNorm05' fit:
%      X Input : xaxis
%      Y Output: curvefit_bayesnorm_05
%  Data for 'BayesNorm09' fit:
%      X Input : xaxis
%      Y Output: curvefit_bayesnorm_09
%  Data for 'TRew01' fit:
%      X Input : rewrange
%      Y Output: curvefit_rewthresh_01
%  Data for 'TRew05' fit:
%      X Input : rewrange
%      Y Output: curvefit_rewthresh_05
%  Data for 'TRew09' fit:
%      X Input : rewrange
%      Y Output: curvefit_rewthresh_09
%  Data for 'BRew01' fit:
%      X Input : rewrange
%      Y Output: curvefit_rewbayes_01
%  Data for 'BRew05' fit:
%      X Input : rewrange
%      Y Output: curvefit_rewbayes_05
%  Data for 'BRew09' fit:
%      X Input : rewrange
%      Y Output: curvefit_rewbayes_09
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Apr-2020 18:02:22

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 12, 1 );
gof = struct( 'sse', cell( 12, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'ThreshNorm01'.
[xData, yData] = prepareCurveData( xaxis, curvefit_threshnorm_01 );

% Set up fittype and options.
ft = fittype( '1/(1+2.71828^(-1*k*(x-x0)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.278498218867048 0.546881519204984];

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'ThreshNorm01' );
h = plot( fitresult{1}, xData, yData );
legend( h, 'curvefit_threshnorm_01 vs. xaxis', 'ThreshNorm01', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'xaxis', 'Interpreter', 'none' );
ylabel( 'curvefit_threshnorm_01', 'Interpreter', 'none' );
grid on

%% Fit: 'ThreshNorm05'.
[xData, yData] = prepareCurveData( xaxis, curvefit_threshnorm_05 );

% Set up fittype and options.
ft = fittype( '1/(1+2.71828^(-1*k*(x-x0)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.970592781760616 0.957166948242946];

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'ThreshNorm05' );
h = plot( fitresult{2}, xData, yData );
legend( h, 'curvefit_threshnorm_05 vs. xaxis', 'ThreshNorm05', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'xaxis', 'Interpreter', 'none' );
ylabel( 'curvefit_threshnorm_05', 'Interpreter', 'none' );
grid on

%% Fit: 'ThreshNorm09'.
[xData, yData] = prepareCurveData( xaxis, curvefit_threshnorm_09 );

% Set up fittype and options.
ft = fittype( '1/(1+2.71828^(-1*k*(x-x0)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.421761282626275 0.915735525189067];

% Fit model to data.
[fitresult{3}, gof(3)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'ThreshNorm09' );
h = plot( fitresult{3}, xData, yData );
legend( h, 'curvefit_threshnorm_09 vs. xaxis', 'ThreshNorm09', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'xaxis', 'Interpreter', 'none' );
ylabel( 'curvefit_threshnorm_09', 'Interpreter', 'none' );
grid on

%% Fit: 'BayesNorm01'.
[xData, yData] = prepareCurveData( xaxis, curvefit_bayesnorm_01 );

% Set up fittype and options.
ft = fittype( '1/(1+2.71828^(-1*k*(x-x0)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.0357116785741896 0.849129305868777];

% Fit model to data.
[fitresult{4}, gof(4)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'BayesNorm01' );
h = plot( fitresult{4}, xData, yData );
legend( h, 'curvefit_bayesnorm_01 vs. xaxis', 'BayesNorm01', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'xaxis', 'Interpreter', 'none' );
ylabel( 'curvefit_bayesnorm_01', 'Interpreter', 'none' );
grid on

%% Fit: 'BayesNorm05'.
[xData, yData] = prepareCurveData( xaxis, curvefit_bayesnorm_05 );

% Set up fittype and options.
ft = fittype( '1/(1+2.71828^(-1*k*(x-x0)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.743132468124916 0.392227019534168];

% Fit model to data.
[fitresult{5}, gof(5)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'BayesNorm05' );
h = plot( fitresult{5}, xData, yData );
legend( h, 'curvefit_bayesnorm_05 vs. xaxis', 'BayesNorm05', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'xaxis', 'Interpreter', 'none' );
ylabel( 'curvefit_bayesnorm_05', 'Interpreter', 'none' );
grid on

%% Fit: 'BayesNorm09'.
[xData, yData] = prepareCurveData( xaxis, curvefit_bayesnorm_09 );

% Set up fittype and options.
ft = fittype( '1/(1+2.71828^(-1*k*(x-x0)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.0318328463774207 0.27692298496089];

% Fit model to data.
[fitresult{6}, gof(6)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'BayesNorm09' );
h = plot( fitresult{6}, xData, yData );
legend( h, 'curvefit_bayesnorm_09 vs. xaxis', 'BayesNorm09', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'xaxis', 'Interpreter', 'none' );
ylabel( 'curvefit_bayesnorm_09', 'Interpreter', 'none' );
grid on

%% Fit: 'TRew01'.
[xData, yData] = prepareCurveData( rewrange, curvefit_rewthresh_01 );

% Set up fittype and options.
ft = fittype( '1/(1+2.71828^(-1*k*(x-x0)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.950222048838355 0.0344460805029088];

% Fit model to data.
[fitresult{7}, gof(7)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'TRew01' );
h = plot( fitresult{7}, xData, yData );
legend( h, 'curvefit_rewthresh_01 vs. rewrange', 'TRew01', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'rewrange', 'Interpreter', 'none' );
ylabel( 'curvefit_rewthresh_01', 'Interpreter', 'none' );
grid on

%% Fit: 'TRew05'.
[xData, yData] = prepareCurveData( rewrange, curvefit_rewthresh_05 );

% Set up fittype and options.
ft = fittype( '1/(1+2.71828^(-1*k*(x-x0)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.795199901137063 0.186872604554379];

% Fit model to data.
[fitresult{8}, gof(8)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'TRew05' );
h = plot( fitresult{8}, xData, yData );
legend( h, 'curvefit_rewthresh_05 vs. rewrange', 'TRew05', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'rewrange', 'Interpreter', 'none' );
ylabel( 'curvefit_rewthresh_05', 'Interpreter', 'none' );
grid on

%% Fit: 'TRew09'.
[xData, yData] = prepareCurveData( rewrange, curvefit_rewthresh_09 );

% Set up fittype and options.
ft = fittype( '1/(1+2.71828^(-1*k*(x-x0)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.709364830858073 0.754686681982361];

% Fit model to data.
[fitresult{9}, gof(9)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'TRew09' );
h = plot( fitresult{9}, xData, yData );
legend( h, 'curvefit_rewthresh_09 vs. rewrange', 'TRew09', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'rewrange', 'Interpreter', 'none' );
ylabel( 'curvefit_rewthresh_09', 'Interpreter', 'none' );
grid on

%% Fit: 'BRew01'.
[xData, yData] = prepareCurveData( rewrange, curvefit_rewbayes_01 );

% Set up fittype and options.
ft = fittype( '1/(1+2.71828^(-1*k*(x-x0)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.162611735194631 0.118997681558377];

% Fit model to data.
[fitresult{10}, gof(10)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'BRew01' );
h = plot( fitresult{10}, xData, yData );
legend( h, 'curvefit_rewbayes_01 vs. rewrange', 'BRew01', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'rewrange', 'Interpreter', 'none' );
ylabel( 'curvefit_rewbayes_01', 'Interpreter', 'none' );
grid on

%% Fit: 'BRew05'.
[xData, yData] = prepareCurveData( rewrange, curvefit_rewbayes_05 );

% Set up fittype and options.
ft = fittype( '1/(1+2.71828^(-1*k*(x-x0)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.585267750979777 0.223811939491137];

% Fit model to data.
[fitresult{11}, gof(11)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'BRew05' );
h = plot( fitresult{11}, xData, yData );
legend( h, 'curvefit_rewbayes_05 vs. rewrange', 'BRew05', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'rewrange', 'Interpreter', 'none' );
ylabel( 'curvefit_rewbayes_05', 'Interpreter', 'none' );
grid on

%% Fit: 'BRew09'.
[xData, yData] = prepareCurveData( rewrange, curvefit_rewbayes_09 );

% Set up fittype and options.
ft = fittype( '1/(1+2.71828^(-1*k*(x-x0)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.959291425205444 0.547215529963803];

% Fit model to data.
[fitresult{12}, gof(12)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'BRew09' );
h = plot( fitresult{12}, xData, yData );
legend( h, 'curvefit_rewbayes_09 vs. rewrange', 'BRew09', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'rewrange', 'Interpreter', 'none' );
ylabel( 'curvefit_rewbayes_09', 'Interpreter', 'none' );
grid on


